features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://Screenshot 2025-08-03 at 1.24.22 PM_0.png'
favicon:
  use_default: 0
  path: ''
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#571B4D'
