_core:
  default_config_hash: 1TswGK46jyu77aIM7Z-0JVQs5bxHmo-gtgrvrQGMXxc
favicon:
  use_default: true
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: false
  node_user_picture: false
logo:
  path: 'public://Screenshot 2025-08-03 at 1.24.22 PM.png'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#571B4D'
